/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRoute } from './routes/__root'
import { Route as AppRoute } from './routes/_app'
import { Route as IndexRoute } from './routes/index'
import { Route as AppDashboardRoute } from './routes/_app.dashboard'
import { Route as AppSignalsRoute } from './routes/_app.signals'
import { Route as AppAgentsRoute } from './routes/_app.agents'
import { Route as AppHeatmapRoute } from './routes/_app.heatmap'
import { Route as AppCopilotRoute } from './routes/_app.copilot'

const AppDashboardRouteImport = AppDashboardRoute.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppSignalsRouteImport = AppSignalsRoute.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)

const AppAgentsRouteImport = AppAgentsRoute.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)

const AppHeatmapRouteImport = AppHeatmapRoute.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AppRoute,
} as any)

const AppCopilotRouteImport = AppCopilotRoute.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)

const IndexRouteImport = IndexRoute.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteImport = AppRoute.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const rootRouteChildren = {
  IndexRoute: IndexRouteImport,
  AppRoute: AppRouteImport,
}
const rootRouteWithChildren = rootRoute._addChildren(rootRouteChildren)

const AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteImport,
  AppSignalsRoute: AppSignalsRouteImport,
  AppAgentsRoute: AppAgentsRouteImport,
  AppHeatmapRoute: AppHeatmapRouteImport,
  AppCopilotRoute: AppCopilotRouteImport,
}
const AppRouteWithChildren = AppRoute._addChildren(AppRouteChildren)

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexRouteImport
    parentRoute: typeof rootRoute
  }
  '/_app': {
    id: '/_app'
    path: ''
    fullPath: ''
    preLoaderRoute: typeof AppRouteImport
    parentRoute: typeof rootRoute
  }
  '/copilot': {
    id: '/copilot'
    path: '/copilot'
    fullPath: '/copilot'
    preLoaderRoute: typeof AppCopilotRouteImport
    parentRoute: typeof AppRouteImport
  }
  '/heatmap': {
    id: '/heatmap'
    path: '/heatmap'
    fullPath: '/heatmap'
    preLoaderRoute: typeof AppHeatmapRouteImport
    parentRoute: typeof AppRouteImport
  }
  '/agents': {
    id: '/agents'
    path: '/agents'
    fullPath: '/agents'
    preLoaderRoute: typeof AppAgentsRouteImport
    parentRoute: typeof AppRouteImport
  }
  '/signals': {
    id: '/signals'
    path: '/signals'
    fullPath: '/signals'
    preLoaderRoute: typeof AppSignalsRouteImport
    parentRoute: typeof AppRouteImport
  }
  '/dashboard': {
    id: '/dashboard'
    path: '/dashboard'
    fullPath: '/dashboard'
    preLoaderRoute: typeof AppDashboardRouteImport
    parentRoute: typeof AppRouteImport
  }
}

export const routeTree = rootRouteWithChildren
